import sys
from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow, QWidget, QLayout, QGridLayout, QPushButton
from PyQt5.QtGui import QPixmap, QTransform
from PyQt5.QtCore import Qt
import PIL.Image
import PyQt5


class Image(QLabel):

    rotation = 0

    def __init__(self, *__args):
        QLabel.__init__(self, *__args)
        self.pixmap = QPixmap('image3.jpeg')
        self.setPixmap(self.pixmap)
        imageData = PIL.Image.open('image.jpeg')
        self.exif_data = imageData._getexif()
        self.rotation = 0

    def resize(self, width, height):
        QLabel.resize(self, width, height)
        pixmap1 = QPixmap('image3.jpeg')
        if width > height:
            self.pixmap = pixmap1.scaled(width, height, Qt.KeepAspectRatio,  Qt.SmoothTransformation)
        else:
            self.pixmap = pixmap1.scaled(height, width, Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.pixmap = self.pixmap.transformed(QTransform().rotate(self.rotation * 90))
        self.setPixmap(self.pixmap)


    def rotate(self, angle):
        self.pixmap = self.pixmap.transformed(QTransform().rotate(angle))
        self.setPixmap(self.pixmap)
        if self.rotation == 3:
            self.rotation = 0
        else:
            self.rotation += 1

    def rotateClockwise(self):
        self.rotate(90)

    def rotateAntiClockwise(self):
        self.rotate(-90)

    def printExif(self):
        print(self.convertExif(self.exif_data))

    def convertExif(self, exif_data):
        result = {}
        exif_data["Camera Manufactureur"] = exif_data.pop(271)
        exif_data["Camera Model"] = exif_data.pop(272)
        exif_data["Generated by"] = exif_data.pop(305)
        for data in exif_data:
            if type(data) != int:
                result[data] = exif_data[data]

        return result


class Window(QWidget):

    def __init__(self):
        QWidget.__init__(self)
        self.label = Image(self)

    def resizeEvent(self, event):
        self.label.resize(self.width(), self.height())


def rotateClockwise():
    width = window.width()
    height = window.height()
    window.resize(height, width)
    image.label.rotateClockwise()

def rotateAntiClockwise():
    pass


if __name__ == '__main__':
    app = QApplication(sys.argv)

    wrapper = QWidget()
    layout = QGridLayout()
    rotateAntiClockwiseButton = QPushButton("ANTI")
    rotateClockwiseButton = QPushButton("ORAR")
    showExifButton = QPushButton("MOSTRA")
    image = Window()

    layout.addWidget(image, 0, 0, 1, 3)
    layout.addWidget(rotateAntiClockwiseButton, 1, 0, 1, 1)
    layout.addWidget(showExifButton, 1, 1, 1, 1)
    layout.addWidget(rotateClockwiseButton, 1, 2, 1, 1)
    rotateClockwiseButton.clicked.connect(rotateClockwise)
    rotateAntiClockwiseButton.clicked.connect(rotateAntiClockwise)
    showExifButton.clicked.connect(image.label.printExif)
    window = QMainWindow()
    wrapper.setLayout(layout)
    window.setCentralWidget(wrapper)
    window.show()
    window.resize(800, 600)
    app.exec_()
