import sys
from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow, QWidget, QLayout, QGridLayout, QPushButton
from PyQt5.QtGui import QIcon, QPixmap, QPainter, QTransform
import PIL.Image

class Image(QLabel):

    def __init__(self):
        QLabel.__init__(self)
        self.pixmap = QPixmap('image.jpeg').scaledToWidth(512)
        self.resize(self.pixmap.width(), self.pixmap.height())
        self.setPixmap(self.pixmap)
        img = PIL.Image.open('image.jpeg')
        self.exif_data = img._getexif()

    def rotate(self, angle):
        self.pixmap = self.pixmap.transformed(QTransform().rotate(angle))
        self.resize(self.pixmap.width(), self.pixmap.height())
        self.setPixmap(self.pixmap)

    def rotateClockwise(self):
        self.rotate(90)

    def rotateAntiClockwise(self):
        self.rotate(-90)

    def printExif(self):
        print(self.convertExif(self.exif_data))

    def convertExif(self, exif_data):
        exif_data["Camera Manufactureur"] = exif_data.pop(271)
        exif_data["Camera Model"] = exif_data.pop(272)
        exif_data["Generated by"] = exif_data.pop(305)
        for data in exif_data:
            print("cavolo" / 1)
        return exif_data

if __name__ == '__main__':
    app = QApplication(sys.argv)

    widget = QWidget()
    layout = QGridLayout()
    rotateAntiClockwiseButton = QPushButton("ANTI")
    rotateClockwiseButton = QPushButton("ORAR")
    showExifButton = QPushButton("MOSTRA")
    image = Image()
    layout.addWidget(image, 0, 0, 1, 3)
    layout.addWidget(rotateAntiClockwiseButton, 1, 0, 1, 1)
    layout.addWidget(showExifButton, 1, 1, 1, 1)
    layout.addWidget(rotateClockwiseButton, 1, 2, 1, 1)
    rotateClockwiseButton.clicked.connect(image.rotateClockwise)
    rotateAntiClockwiseButton.clicked.connect(image.rotateAntiClockwise)
    showExifButton.clicked.connect(image.printExif)
    window = QMainWindow()
    widget.setLayout(layout)
    window.setCentralWidget(widget)
    window.show()
    app.exec_()
